name: Daily Issue Update

on:
  schedule:
    # Run at 8:00 AM IST daily (IST = UTC + 5:30)
    - cron: '30 11 * * *'  # 2:30 AM UTC = 8:00 AM IST

jobs:
  update-issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest commit
      id: latest_commit
      run: |
        echo "LATEST_COMMIT=$(git log -1 --pretty=format:'%h - %s')" >> $GITHUB_ENV

    - name: List all open issues
      id: open_issues
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await github.paginate(
            github.rest.issues.listForRepo,
            { owner: context.repo.owner, repo: context.repo.repo, state: 'open' }
          );
          return { issue_numbers: issues.map(issue => issue.number) };

    - name: Comment on each open issue
      uses: actions/github-script@v6
      with:
        script: |
          const latestCommit = process.env.LATEST_COMMIT;
          const issues = ${{ toJson(steps.open_issues.outputs.issue_numbers) }};

          for (const issueNumber of issues) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `🔄 The repository has been updated! The latest commit is: **${latestCommit}**. Please pull the latest changes from the remote repository to stay up-to-date.`
            });
          }
